### ISSUE TITLE
Not all audio codecs are being returned in json output

### ISSUE THREAD

**Issue by chakrikodali** [videojs/mpd-parser#105]
I have mpd with both ac-3 and mp4a.40.5 - ac-3 codec is not supported by browsers. 

Is it possible to specify the audio track/codec to be used from mpd file? Looking at the code MPDparser picks the last audio track by default. https://github.com/videojs/mpd-parser/blob/main/src/toM3u8.js#L124

**Comment by gkatsev** [comment]
This library is purely about having a representation of the mpd in JSON for usage. In our usage of it in VHS we make sure to not select codecs that aren't supported in the browser.
Are you using mpd-parser directly? If so, you'll need to filter the renditions yourself. If you're seen an issue with the default audio in VHS, we'll definitely take a look.

**Comment by chakrikodali** [comment]
I am using vhs 1.13.4 and it doesn't have support to pick the audio codec yet. Looks like 2.2.x filters out unsupported codecs.

**Comment by chakrikodali** [comment]
Reopening this - @gkatsev yes in 2.2.x of vhs unsupported audio codecs are being filtered out. But mpd-parser is picking only one audio adaption set which can ac-3  and playback gets stalled. https://github.com/videojs/mpd-parser/blob/v0.12.0/src/toM3u8.js#L124 . As you mentioned ideally mpd-parser should return all the available audio adaption sets and let vhs filter it out.

**Comment by amatorecorrado** [comment]
I found another example of the issue, in this shaka player demo stream, the audio 64k are not in json output: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
