### ISSUE TITLE
How to calculate current live segment

### ISSUE THREAD

**Issue by quickstreamingmedia** [videojs/mpd-parser#121]
I have dynamic list how to calculate current live segment

**Comment by Temo887** [comment]
can this open the hidden manifest resolution?

**Comment by quickstreamingmedia** [comment]
I need most recent segment

**Comment by quickstreamingmedia** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" id="1460881" type="dynamic" publishTime="2021-02-25T16:42:34" minimumUpdatePeriod="PT30S" availabilityStartTime="2018-10-22T12:02:06.387000+00:00" minBufferTime="PT30S" suggestedPresentationDelay="PT25.00S" timeShiftBufferDepth="PT3639.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period start="PT0.00S" id="1">
    <AdaptationSet mimeType="video/mp4" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="true">
      <Representation id="1" width="480" height="360" frameRate="25/1" bandwidth="1200000" codecs="avc1.4D401E">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="25" media="1460881_video_1_0_$Number$.mp4?m=1612386835" initialization="1460881_video_1_0_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="1851450040" d="200" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="2" width="480" height="360" frameRate="25/1" bandwidth="800000" codecs="avc1.42E01E">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="25" media="1460881_video_1_1_$Number$.mp4?m=1612386835" initialization="1460881_video_1_1_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="1851450040" d="200" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="3" width="360" height="270" frameRate="25/1" bandwidth="400000" codecs="avc1.42E015">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="25" media="1460881_video_1_2_$Number$.mp4?m=1612386835" initialization="1460881_video_1_2_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="1851450040" d="200" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="4" width="234" height="176" frameRate="25/1" bandwidth="180000" codecs="avc1.42E00C">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="25" media="1460881_video_1_3_$Number$.mp4?m=1612386835" initialization="1460881_video_1_3_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="1851450040" d="200" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet mimeType="audio/mp4" segmentAlignment="0">
      <Representation id="5" bandwidth="98756" audioSamplingRate="48000" codecs="mp4a.40.2">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="48000" media="1460881_audio_1_4_$Number$.mp4?m=1612386835" initialization="1460881_audio_1_4_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="3554784077455" d="384000" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="6" bandwidth="98756" audioSamplingRate="48000" codecs="mp4a.40.2">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="48000" media="1460881_audio_1_5_$Number$.mp4?m=1612386835" initialization="1460881_audio_1_5_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="3554784077455" d="384000" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="7" bandwidth="98604" audioSamplingRate="48000" codecs="mp4a.40.2">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="48000" media="1460881_audio_1_6_$Number$.mp4?m=1612386835" initialization="1460881_audio_1_6_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="3554784077455" d="384000" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="8" bandwidth="98678" audioSamplingRate="48000" codecs="mp4a.40.2">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="2279EB85-599C-4464-AA2C-B532EDCAAB3E" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8IARIQInnrhVmcRGSqLLUy7cqrPiIJNDAwMDAwMDAx</cenc:pssh>
        </ContentProtection>
        <SegmentTemplate timescale="48000" media="1460881_audio_1_7_$Number$.mp4?m=1612386835" initialization="1460881_audio_1_7_init.mp4?m=1612386835" startNumber="36279284">
          <SegmentTimeline>
            <S t="3554784077455" d="384000" r="453"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
`

 can any one tell me how to get live segment from this

**Comment by quickstreamingmedia** [comment]
can someone get me formula for this mpd to get to live cause now using start number going 1 hour behind

https://pastebin.com/Q6Bbpw3n
