### ISSUE TITLE
xmldom vulnerability

### ISSUE THREAD

**Issue by japettyjohn** [videojs/mpd-parser#124]
The version of xmldom depended on has a [vulnerability](https://www.npmjs.com/advisories/1650) which has since been fixed. The dependency needs to be updated to a later version of xmldom.

**Comment by eliamartani** [comment]
It is already fixed https://github.com/videojs/mpd-parser/commit/e132e4045dd847b414f68b07a8892ce93d70af05.

We just need the version `0.15.5` to be released with it.

**Comment by heennkkee** [comment]
Looking forward to the release of that version!

**Comment by eliamartani** [comment]
hey,

version `0.16.0` was released, meaning the issue is fixed.

**Comment by brandonocasey** [comment]
You are correct.
