### ISSUE TITLE
DASH_INVALID_XML error

### ISSUE THREAD

**Issue by beta2k** [videojs/mpd-parser#126]
My HTML looks like this:

![image](https://user-images.githubusercontent.com/1133118/112368537-7a267800-8cdb-11eb-818a-372be98c7087.png)

However, I get this error:

![image](https://user-images.githubusercontent.com/1133118/112368599-89a5c100-8cdb-11eb-8445-5a05a1de2f6b.png)

The MPD URL is
> https://cdxaws-ak.akamaized.net/out/v1/23240f1b2b1242ac8226d6f1a8653bfc/469c706849ff410385e5d65308566647/5e2a57fc0380466b9864849ce3f168ea/manifest.mpd

What am I doing wrong?

**Comment by gkatsev** [comment]
Looks like our example is slightly misleading. Specifically, it doesn't make any network calls itself to download the manifest, you must download it yourself and provide it to mpd-parser. (I think the `<>` in the example was supposed to be a stand-in for a manifest).
Currently, `parse` accepts the string value of the manifest and an options object. Looks like our example is actually out of date with the current state of the module.
Should be something like:
```
const manifestUri = 'https://cdxaws-ak.akamaized.net/out/v1/23240f1b2b1242ac8226d6f1a8653bfc/469c706849ff410385e5d65308566647/5e2a57fc0380466b9864849ce3f168ea/manifest.mpd');
const res = await fetch(manifestUri);
const mpdString = await res.text();
mpdParser.parse(mpdString, { manifestUri });
```

**Comment by beta2k** [comment]
Ah okay, that makes sense then. So I have the raw MPD, but I need to escape everything such as quotes when feeding it into the `manifest` variable?

**Comment by beta2k** [comment]
Hm, now I convert all of the following characters to entities: ", <, > and &.
Furthermore I removed all line breaks.

HTML looks like this:

![image](https://user-images.githubusercontent.com/1133118/112371659-274ebf80-8cdf-11eb-81c5-6b6ea8190510.png)

Still I get this error:

![image](https://user-images.githubusercontent.com/1133118/112371704-36ce0880-8cdf-11eb-8e32-bbd3e7ce4bb8.png)

**Comment by gkatsev** [comment]
you don't need to encode those entities. You just want the literal string representation of the manifest. The easiest way to get it is to download it from the url you have and then pass that response text into the mpd parser.

**Comment by beta2k** [comment]
Thanks for your help. Maybe I'm being slow here, but don't I at least have to esacpe double quote and line breaks? because if I simply copy+paste the content of the MPD into the HTML, I get:

> Uncaught SyntaxError: Invalid or unexpected token

**Comment by beta2k** [comment]
Of course, I could fetch it ;) Sorry, I was thinking to complicated. Anyway, got it to work now by escaping double quotes and removing line breaks. Thanks!
