### ISSUE TITLE
Security vulnerability in xmldom

### ISSUE THREAD

**Issue by andrewspinks** [videojs/mpd-parser#143]
npm is reporting a security vulnerability in a xmldom which is causing npm audit to fail for users of video.js and mpd-parser. https://www.npmjs.com/advisories/1769

![security-vuln](https://user-images.githubusercontent.com/1097463/128102968-a9a1c81b-14b6-488d-9f47-c10f96504a95.png)

Unfortunately, a fix has not yet been published, so I cannot open a PR to address this yet. https://github.com/xmldom/xmldom/issues/271

**Comment by gkatsev** [comment]
It's worth noting that xmldom isn't used by mpd-parser in the built files that run on a webpage. It's only used by mpd-parser if you use it via the CLI or via node.js directly.

**Comment by dj-documentation** [comment]
videojs/video.js#7389

**Comment by dj-documentation** [comment]
Leaving video.js and mpd-parser unpatched trains users to ignore `npm audit`, `yarn audit`, and GitHub warnings.

![image](https://user-images.githubusercontent.com/88207951/130304267-d6d860fa-1b43-43b5-b19a-e5d3a09aaf7f.png)

**Comment by dj-documentation** [comment]
xmldom is now @xmldom/xmldom

https://github.com/xmldom/xmldom/issues/271
