### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Makio64** [videojs/mpd-parser#172]
Hello,

According to snyk.io, video js present a security issue cause by xmldom@0.7.6 imported by mpd-parser, updating to 0.7.7 would fix it.

Thanks

**Comment by mister-ben** [comment]
0.7.7 is not being used by current versions.

https://github.com/videojs/mpd-parser/blob/af9969f05985629b8fde6e70402dee58103a28f7/package.json#L60
