### ISSUE TITLE
UNSUPPORTED_SEGMENTATION_TYPE Error: UNSUPPORTED_SEGMENTATION_TYPE

### ISSUE THREAD

**Issue by mesutyigit** [videojs/mpd-parser#5]
I try this mpd manifest file  , throw this error

https://s3-eu-west-1.amazonaws.com/hivecdn.digiturk.video.io.ireland/out/progressive1.mp4/progressive1.mpd

**Comment by forbesjo** [comment]
This parser currently doesn't support `SegmentBase`, this is on our roadmap.

**Comment by forbesjo** [comment]
Will be fixed by https://github.com/videojs/mpd-parser/pull/18

**Comment by forbesjo** [comment]
Will require another update to support segment lists within Representations

**Comment by gkatsev** [comment]
Looks like the final piece if the SIDX PR: #41
