### ISSUE TITLE
Resolveduri Wrong

### ISSUE THREAD

**Issue by mesutyigit** [videojs/mpd-parser#6]
At parsed manifest data ,  all resolved uris wrong normalized.  
site  running at : http://mesut.ofis:4000
mpd file: http://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

parsed Playlist first resolved uri :  http://mesut.ofis:4000/video/180_250000/dash/init.mp4  

location.origin + segment uri  -> wrong 
manifest uri base  + segment uri -> done

**Comment by forbesjo** [comment]
The "usage" section is out of date (https://github.com/videojs/mpd-parser#usage) the function takes two arguments, the manifest content and the manifest URL. Are you providing the URL argument?

**Comment by mesutyigit** [comment]
I did it depend on docs  , now url provide to second argument this fixed.
