### ISSUE TITLE
Incorrect total number of audio tracks

### ISSUE THREAD

**Issue by LienLotus** [videojs/mpd-parser#95]
In the manifest file:
Total audio tracks are 8 tracks
But using mpd-parser, total audio tracks are 4 tracks
```
const mpdParser = require('mpd-parser');
mpdParser.parse(response.body)
audio_tracks_counter = Object.keys(parsedManifest.mediaGroups.AUDIO.audio).length;
```
![Screenshot from 2020-04-08 17-15-43](https://user-images.githubusercontent.com/51039899/78772863-97741080-79bc-11ea-9c10-a67742c94fb2.png)

Note: response.body is the content of the manifest file (in the attachment)
Env: Ubuntu 18.04, mpd-parser version 0.10.1

[manifest.txt](https://github.com/videojs/mpd-parser/files/4449794/manifest.txt)

**Comment by gkatsev** [comment]
Closing this in favor of #77 because they are duplicates. We're going to try and look at this soon because it's definitely an important thing to get right.
