### ISSUE TITLE
Wrong resolvedUri

### ISSUE THREAD

**Issue by gdavila** [videojs/mpd-parser#98]
Hi, I'm trying the code provided in this example  [videojs.github.io/mpd-parser]( https://videojs.github.io/mpd-parser/) and passing to it the url `https://dash.edgesuite.net/akamai/bbb_30fps/bbb_30fps.mpd`. However,  the `resolvedUri` in the returned parser manifest seems to be wrong.

I. e., `parsedMpd.playlists[0].segments[0]`
```
map: {uri: "bbb_30fps_1024x576_2500k/bbb_30fps_1024x576_2500k_0.m4v", resolvedUri: "https://videojs.github.io/mpd-parser/bbb_30fps_1024x576_2500k/bbb_30fps_1024x576_2500k_0.m4v"}
number: 1
resolvedUri: "https://videojs.github.io/mpd-parser/bbb_30fps_1024x576_2500k/bbb_30fps_1024x576_2500k_1.m4v"
timeline: 0
uri: "bbb_30fps_1024x576_2500k/bbb_30fps_1024x576_2500k_1.m4v"
```
I was expected a `resolvedUri` such as `https://dash.edgesuite.net/akamai/bbb_30fps/bbb_30fps_1024x576_2500k/bbb_30fps_1024x576_2500k_0.m4v`. Am I misunderstanding something?

**Comment by gkatsev** [comment]
I believe that this is fixed now. I think the issue was actually that the gh-pages page was using the old API. With https://github.com/videojs/mpd-parser/pull/128, the resolvedUri is showing up correctly.
